### ISSUE TITLE
docs on remote pair-programming tools, e.g. vs-code live share?

### ISSUE THREAD

**Issue by dckc** [rchain/hackathon-2020#1]
I just got [vs-code Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) working, based on a suggestion from @TheoXD . (I use the open source vs-codium rather than the normal vs-code that phones home with telemetry, so I had to pay some open source tax by fidgeting with clues from https://github.com/VSCodium/vscodium/issues/320 but I'm happier to pay that tax than the surveillance capitalism tax :)

I'm inclined to recommend this for hackathon support. I thought about a blog item on rholang.github.io , but if somebody wants to document it on rchain.coop , that could work too.

**Comment by 9rb** [comment]
recommend vs-code Live Share .. just add above link (to the microsoft Live Share documentation) to the hackathon page  https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare

**Comment by 9rb** [comment]
Also add https://rhobot.net/LearnRholangByExample link in the learning resources and test

**Comment by SteveHenley** [comment]
Created pr for vc-live share and learn rholang by example links.

**Comment by SteveHenley** [comment]
Links added
