### ISSUE TITLE
office hours / support schedule

### ISSUE THREAD

**Issue by dckc** [rchain/hackathon-2020#12]
Identify hackathon helpers. It seems worthwhile to have certain times and people scheduled for support.

**Comment by 9rb** [comment]
Potential Hackathon schedule:

1. Forming teams - hopefully ahead of the hackathon, during the mentoring sessions. Last minute teams may be formed during / after kickoff
2. Nov 6 Friday - Kickoff (decide on presenters) - 9 pm Eastern Friday (Saturday Nov 7, 7:30 AM IST) - need to create agenda. Remind them to be prepared by 4 pm, including completing their presentation
3. Hackathon - Greg, Tomislav, nutzipper, Will, SteveH, Theo, Jimscarver, Dckc, Rao, Ian, Darryl, Arthur Greef, Raphael, Eric Meng, AtticBee, Tobi ?, Steve RT 
4. Team presentations - 8 minutes per team (total : 2.5 to 3 hrs?)
5. Judging - (need templates + judges for judging) - starts at 1 pm continues through presentations and then consensus and verification of results before announcing.
6. Concluding remarks - We might want to conclude at Sunday 10 am US Eastern (IST 8:30 PM Sunday).. start speeches by 8 PM IST

Everyone's free after Sunday noon Eastern.
Rao available both Nov 7 and Nov 8,  5 am to 10 pm US Eastern (3:30 PM IST till 8:30 AM IST) - other than meals breaks
**SteveH** - Available Nov 6th 9pm (EST) (kickoff), Nov 7th 5am to 10 pm (EST), Nov 8th 5am to 10am (EST)

**Comment by TheoXD** [comment]
I'm 4.5 hours behind so mornings don't really work well for me, but from 3 or 4 PM IST I'm available.

**Comment by dckc** [comment]
@9rb writes: 
> 2. Nov 6 Friday - Kickoff (decide on presenters) - ... need to create agenda. Remind them to be prepared by 4 pm, including completing their presentation

@9rb please do create an agenda right away. We're getting down to the wire.
