### ISSUE TITLE
hackathon chat logistics? Discord? Zulip?

### ISSUE THREAD

**Issue by dckc** [rchain/hackathon-2020#2]
@jimscarver and I were wondering about a hackathon discord server with a channel per team... or the https://zulip.rchain-dev.tk/ Zulip ...

As much as I like the idea of self-hosting, I don't think we've put enough resource behind zulip.rchain-dev to make it critical to the hackathon.

As for Discord... I realized (from watching my kids) that the norm is that each team / guild makes its own _server_. I built my chat habits on IRC where anyone can create a channel but only the gods can make servers; discord is sort of "inside out" from that: anyone can make a server, but only the (local server) gods can make a channel. The [discord API docs](https://discord.com/developers/docs/resources/guild#guild-resource) actually say:

> Guilds in Discord represent an isolated collection of users and channels, and are often referred to as "servers" in the UI.

So I suggest we tell the teams (a) there are lots of collaboration tools out there; pick your favorites. (b) the RChain coop primarily uses discord to date, so the support folks are likely to be familiar with it. Feel free to use the public channels in the RChain discord server (#development, #rholang, #education, etc.), or make your own server for your team, or both.

**Comment by 9rb** [comment]
Let's just use the Discord channels for now. Also need to add the discord link at the bottom of the hackathon page.

**Comment by ian-bloom** [comment]
Added: #23

"Chat with us in our [#hackathon-2020](https://discord.com/channels/375365542359465989/748967102840569886) channel on Discord <a href="https://discord.gg/NWkQnfH">(Invitation Link)</a>."
