### ISSUE TITLE
Remove the long running examples from Rholang Plaground examples

### ISSUE THREAD

**Issue by 9rb** [rchain/hackathon-2020#4]
Remove from the drop down list the rholang programs that take too long to run. This is supposed to be an interactive learning experience for newbies to Rholong, so long running programs do not belong in this list.  Work w/ nutzipper to identify the fast examples and remove the rest (e.g. dupe.rho and slow.rho etc.)
Include Joshy's examples as part of the list - we need a short list

**Comment by dckc** [comment]
@9rb  while you're at it, I suggest adding the ones in https://github.com/rchain/developer.rchain.coop/pull/10

**Comment by 9rb** [comment]
Both the above items are completed by nutzipper. We can now see Dan's new examples at the bottom of the list and the long running ones removed from the top list. Rao tested and everything seems to work as expected.
