### ISSUE TITLE
Fix Rholang Plaground examples to have the output go to the exploratory deploy return channel

### ISSUE THREAD

**Issue by 9rb** [rchain/hackathon-2020#5]
In the Rholang code, stdout should be replaced by correct syntax for return . Additionally, CSS changes may be needed to make this work correctly on the screen.
Include Joshy's examples as part of the list - we need a short list

**Comment by 9rb** [comment]
Also the program links should refer to the rchain-community links and not Joshy's repo @SteveHenley

**Comment by jimscarver** [comment]
done
