### ISSUE TITLE
document testnet faucet

### ISSUE THREAD

**Issue by dckc** [rchain/hackathon-2020#8]
link to https://status.rchain.coop/testnet/faucet/ from https://rchain.coop/hackathon#dev-apis

is it documented anywhere from developer.rchain.coop ? I couldn't find it with a web search. I found it on https://blog.rchain.coop/2020/10/14/voting-on-rchain/

**Comment by ian-bloom** [comment]
added faucet link to [https://rchain.coop/hackathon](https://rchain.coop/hackathon)

[rchain/www.rchain.coop/pull/26](https://github.com/rchain/www.rchain.coop/pull/26)
