### ISSUE TITLE
feature "Voting in Rholang" rv2020 slides / video / beta app / source code

### ISSUE THREAD

**Issue by dckc** [rchain/hackathon-2020#9]
In the [Oct 13 comms notes](https://docs.google.com/document/d/1yrCqj5GWKElRVGYrPcrRDOEAZl4ILk3RYv00GFo6Yts/edit#heading=h.ubrw49ows1bi) I see:

RChat / RVote: current status? Dan’s Voting in Rholang slides: https://docs.google.com/presentation/d/1LLwejP0QdhHwhjYd-LFIPBblj1owjBGHBgL_EWh80V8/edit#slide=id.g9c72ba371b_0_1247 I edited, uploaded to youtube  and posted it on the Blog - https://blog.rchain.coop/2020/10/07/rchain-voting-in-rholang/  link still needs to go onto the hackathon page.

cc @9rb @ian-bloom @OPNO

**Comment by 9rb** [comment]
Add https://status.rchain.coop/testnet/faucet/ to the devtools section on the hackathon page

**Comment by ian-bloom** [comment]
> Add https://status.rchain.coop/testnet/faucet/ to the devtools section on the hackathon page

Added to https://rchain.coop/hackathon "RChain Platform" Section on 10/30

**Comment by ian-bloom** [comment]
> In the [Oct 13 comms notes](https://docs.google.com/document/d/1yrCqj5GWKElRVGYrPcrRDOEAZl4ILk3RYv00GFo6Yts/edit#heading=h.ubrw49ows1bi) I see:
> 
> RChat / RVote: current status? Dan’s Voting in Rholang slides: https://docs.google.com/presentation/d/1LLwejP0QdhHwhjYd-LFIPBblj1owjBGHBgL_EWh80V8/edit#slide=id.g9c72ba371b_0_1247 I edited, uploaded to youtube and posted it on the Blog - https://blog.rchain.coop/2020/10/07/rchain-voting-in-rholang/ link still needs to go onto the hackathon page.
> 
> cc @9rb @ian-bloom @OPNO

(self assigning to @ian-bloom )

**Comment by ian-bloom** [comment]
Link to blog article added to https://rchain.coop/hackathon
Google Slideshow link added to https://blog.rchain.coop/2020/10/14/voting-on-rchain/
